import Actor from '../../../core/message/actor';
import { MultiProjectMeta, Project } from '../types/types';
import Dispatcher from '../../../core/message/dispatcher';
import { Callback } from '../../../core/types';
import { GridContext } from '@/core/grid/types';
import { boundingBox2D } from '@/core/util/boundingBox2D';
import GridCore from '@/core/grid/NHGridCore';
import store from '../../../store';
import { MultiGridRenderInfo } from '@/core/grid/types';
import TopologyLayer from '@/components/mapComponent/layers/TopologyLayer';
import NHLayerGroup from '@/components/mapComponent/utils/NHLayerGroup';
import { PatchMeta } from '@/core/apis/types';